LibMan/Controllers/Api/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using LibMan.Models;

namespace LibMan.Controllers.Api
{
    public class BooksController : ApiController
    {
        private readonly ApplicationDbContext _db;

        public BooksController()
        {
            _db = new ApplicationDbContext();
        }
        //Get /api/books
        public IEnumerable<Book> GetBooks()
        {
            return _db.Books.ToList();
        }


        //GET /api/books/1
        public IHttpActionResult GetBooks(int id)
        {
            var book = _db.Books.SingleOrDefault(b => b.BookId == id);
            if (book == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            return Ok(book);
        }

        //POST /api/books
        [HttpPost]
        public IHttpActionResult CreateBook(Book book)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            _db.Books.Add(book);
            _db.SaveChanges();
            return Ok(book);
        }

        //PUT /api/books/1
        [HttpPut]
        public IHttpActionResult UpdateBook(int id, Book book)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            var bookInDb = _db.Books.SingleOrDefault(b => b.BookId == id);
            if (bookInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            bookInDb.Title = book.Title;
            bookInDb.Author = book.Author;
            bookInDb.Publisher = book.Publisher;
            bookInDb.ImageAddress = book.ImageAddress;
            bookInDb.NumberInStock = book.NumberInStock;
            bookInDb.YearPublished = book.YearPublished;
            bookInDb.Page = book.Page;
            bookInDb.CategoryId = book.CategoryId;
            _db.SaveChanges();
            return Ok(bookInDb);
        }



        //DELETE /api/books/1
        [HttpDelete]
        public IHttpActionResult DeleteBook(int id)
        {
            var bookInDb = _db.Books.SingleOrDefault(b => b.BookId == id);
            if (bookInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            _db.Books.Remove(bookInDb);
            _db.SaveChanges();
            return Ok();

        }

    }
}

LibMan/Controllers/Api/BorrowersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace LibMan.Models.Api
{
    public class BorrowersController : ApiController
    {
        private readonly ApplicationDbContext _db;

        public BorrowersController()
        {
            _db = new ApplicationDbContext();
        }

        //Get /api/borrowers
        public IEnumerable<Borrower> GetBorrowers()
        {
            return _db.Borrowers.ToList();
        }


        //GET /api/borrowers/1
        public IHttpActionResult GetBorrowers(int id)
        {
            var borrower = _db.Borrowers.SingleOrDefault(b => b.Id == id);
            if (borrower == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            return Ok(borrower);
        }

        //POST /api/borrowers
        [HttpPost]
        public IHttpActionResult CreateBorrower(Borrower borrower)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            _db.Borrowers.Add(borrower);
            _db.SaveChanges();
            return Ok(borrower);
        }

        //PUT /api/borrowers/1
        [HttpPut]
        public IHttpActionResult UpdateBorrowe(int id, Borrower borrower)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            var borrowerInDb = _db.Borrowers.SingleOrDefault(b => b.Id == id);
            if (borrowerInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            borrowerInDb.Name = borrower.Name;
            borrowerInDb.Surname = borrower.Surname;
            borrowerInDb.NationalId = borrower.NationalId;
            borrowerInDb.BirthDate = borrower.BirthDate;
            borrowerInDb.Address = borrower.Address;
            borrowerInDb.Phone = borrower.Phone;
            _db.SaveChanges();
            return Ok(borrowerInDb);
        }



        //DELETE /api/borrowers/1
        [HttpDelete]
        public IHttpActionResult DeleteBorrower(int id)
        {
            var borrowerInDb = _db.Borrowers.SingleOrDefault(b => b.Id == id);
            if (borrowerInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            _db.Borrowers.Remove(borrowerInDb);
            _db.SaveChanges();
            return Ok();

        }
    }
}

LibMan/Views/Shared/_Layout.cshtml
@using LibMan.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @if (User.IsInRole(RoleName.CanManage))
    {
        @Html.Partial("_NavBar");
    }
    else
    {
        @Html.Partial("_NavBarRO");
    }
       
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LibMan <i class="fas fa-book-open"></i></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibMan/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("LibMan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Borrowers <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Borrowers", "Index", "Borrowers")</li>
                        <li>@Html.ActionLink("New Borrower", "New", "Borrowers")</li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Books <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Books", "Index", "Books")</li>
                        <li>@Html.ActionLink("New Book", "New", "Books")</li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Lends <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Lends", "Index", "Lends")</li>
                        <li>@Html.ActionLink("New Lend", "SelectBorrower", "Lends")</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

LibMan/Views/Shared/_NavBarRO.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("LibMan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Borrowers <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Borrowers", "Index", "Borrowers")</li>
                        </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Books <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Books", "Index", "Books")</li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Lends <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("List of Lends", "Index", "Lends")</li>
                       </ul>
                </li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>